backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/media" # Media files will be stored in the repo under images/uploads
public_folder: "./media" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Leadership Team"
    name: "Leadership Team"
    files:
      - label: "Leadership Team"
        name: "leadership_team"
        file: "src/posts/leadership_team.json"
        fields:
          - label: Positions
            name: positions
            widget: list
            fields:
              - {label: Positions Category, name: positions_category, widget: string}
              - label: People
                name: people
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Official Title, name: title, widget: string}
                  - {label: Bio, name: bio, widget: text}
                  - {label: Photo, name: photo, widget: image}